import React, { Component } from 'react';
import ReactDOM from 'react-dom';
import Start from './components/Start.js';

// Create a new component

class App extends Component {
	constructor() {
		super();

		this.state = {
		}
	}

	render() {
		return (
			<div>
				<Start />
			</div>
		)
	}
}


// Make sure the HTML generated by the component is on the page (the DOM)

ReactDOM.render(<App />, document.querySelector('.container'));