import React, { Component } from 'react';
import ReactDOM from 'react-dom';

// Create a new component

class App extends Component {
	constructor() {
		super();
		this.state = {
		}
	}

	render() {
		return (
			<div>
				Ali
			</div>
		)
	}
}


// Make sure the HTML generated by the component is on the page (the DOM)
ReactDOM.render(<App />, document.querySelector('.container'));
