import React, { Component } from 'react';
import {Router, Route, hashHistory, IndexRedirect, IndexRoute} from 'react-router';
import ReactDOM from 'react-dom';
import Start from './components/Start';
import Flashcard from './components/Flashcard';

// Create a new component

class App extends Component {
	constructor() {
		super();
		this.state = {
		}
	}

	render() {
		return (
			<div>
				{ this.props.children }
			</div>
		)
	}
}


// Make sure the HTML generated by the component is on the page (the DOM)
ReactDOM.render(
	<Router history={hashHistory}>
      <Route path="/" component={App}>
        <Route path="/start" component={Start}/>
        <IndexRedirect to="/start"/>
				<Route path="/flashcard" component={flashcard}/>
      </Route>
  </Router>, document.querySelector('.container'));
